management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  server:
    port: 8081

# The path, relative to the server root, where this application will deploy.
server:
  use-forward-headers: true
  servlet:
    context-path: /t65-squad-builder

# Disables Spring Boot integration for Keycloak by default.
keycloak:
  enabled: false

tcashcroft:
  t65-squad-builder: {}